Agencia/Models/Habitaciones.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agencia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Habitaciones
    {
        public int id { get; set; }
        public Nullable<int> hotel { get; set; }
        public Nullable<int> tipoHabitacion { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public Nullable<double> costo { get; set; }
        public Nullable<double> impuesto { get; set; }
        public Nullable<int> numeroAdultos { get; set; }
        public Nullable<int> numeroNiños { get; set; }
        public Nullable<int> totalPersonas { get; set; }
        public Nullable<int> ubicacion { get; set; }
        public Nullable<int> estado { get; set; }        
        public Nullable<System.DateTime> fechaEntrada { get; set; }
        public Nullable<System.DateTime> fechaSalida { get; set; }

        public virtual Estados Estados { get; set; }
        public virtual Hoteles Hoteles { get; set; }
        public virtual tiposHabitaciones tiposHabitaciones { get; set; }
        public virtual Ubicacion Ubicacion1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reservas> Reservas { get; set; }
    }
}

Agencia/Controllers/HabitacionesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Agencia.Models;
using Agencia.Permisos;

namespace Agencia.Controllers
{
    [ValidateSessionAtribute]
    public class HabitacionesController : Controller
    {
        private AGENCIAModelado db = new AGENCIAModelado();

        // GET: Habitaciones
        public ActionResult Index(string searchString = "", string filtro = "")
        {
            var habitaciones = db.Habitaciones.Include(h => h.Estados).Include(h => h.Hoteles).Include(h => h.tiposHabitaciones).Include(h => h.Ubicacion1)
                .Where(h => h.Hoteles.estado == 1).Where(ha => ha.estado == 1);


            if (!String.IsNullOrEmpty(searchString) && !String.IsNullOrEmpty(filtro))
            {
                switch (filtro)
                {
                    case "hotel":
                        habitaciones = habitaciones.Where(s => s.Hoteles.nombre.Contains(searchString));
                        break;

                    case "fechaEntrada":                        
                        habitaciones = habitaciones.Where(s => Convert.ToDateTime(s.fechaEntrada).ToShortDateString() == (Convert.ToDateTime(searchString).ToShortDateString()));
                        break;

                    case "fechaSalida":
                        habitaciones = habitaciones.Where(s => Convert.ToDateTime(s.fechaSalida).ToShortDateString() == (Convert.ToDateTime(searchString).ToShortDateString()));
                        break;

                    case "totalPersonas":
                        habitaciones = habitaciones.Where(s => s.totalPersonas == int.Parse(searchString));
                        break;

                    case "ciudad":
                        habitaciones = habitaciones.Where(s => s.Hoteles.ciudad.Contains(searchString));
                        break;
                }                                    
            }

            var usuario = db.Usuarios.Find(Session["usuario"]);

            ViewBag.reservas = (from hoteles in db.Hoteles
                                join reservas in db.Reservas on hoteles.id equals reservas.hotel
                                join _habitaciones in db.Habitaciones on reservas.habitacion equals _habitaciones.id
                                select new ModelNew
                                {
                                    id = reservas.id,
                                    fechaEntrada = reservas.fechaEntrada,
                                    fechaSalida = reservas.fechaSalida,
                                    cantidadPersonas = reservas.cantidadPersonas,
                                    ciudadDestino = reservas.ciudadDestino,
                                    nombreEmergencia = reservas.nombreEmergencia,
                                    apellidoEmergencia = reservas.apellidoEmergencia,
                                    telefomoEmergencia = reservas.telefomoEmergencia,
                                    nombre_usuario = usuario.nombres + " " + usuario.apellidos,
                                    nombre_hotel = hoteles.nombre,
                                    nombre_habitacion = _habitaciones.nombre,
                                }).ToArray();
              

            return View(habitaciones.ToList());
        }

        public ActionResult Lista()
        {
            var habitaciones = db.Habitaciones.Include(h => h.Estados).Include(h => h.Hoteles).Include(h => h.tiposHabitaciones).Include(h => h.Ubicacion1)
                .Where(h => h.Hoteles.estado == 1).Where(ha => ha.estado == 1);
            return View(habitaciones.ToList());

        }

        // GET: Habitaciones/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Habitaciones habitaciones = db.Habitaciones.Find(id);
            if (habitaciones == null)
            {
                return HttpNotFound();
            }
            return View(habitaciones);
        }

        // GET: Habitaciones/Create
        public ActionResult Create()
        {
            ViewBag.estado = new SelectList(db.Estados, "id", "nombre");
            ViewBag.hotel = new SelectList(db.Hoteles, "id", "nombre");
            ViewBag.tipoHabitacion = new SelectList(db.tiposHabitaciones, "id", "nombre");
            ViewBag.ubicacion = new SelectList(db.Ubicacion, "id", "nombre");
            return View();
        }

        // POST: Habitaciones/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,hotel,tipoHabitacion,nombre,descripcion,costo,impuesto,numeroAdultos,numeroNiños,totalPersonas,ubicacion,estado")] Habitaciones habitaciones)
        {
            if (ModelState.IsValid)
            {
                db.Habitaciones.Add(habitaciones);
                db.SaveChanges();
                return RedirectToAction("Lista");
            }

            ViewBag.estado = new SelectList(db.Estados, "id", "nombre", habitaciones.estado);
            ViewBag.hotel = new SelectList(db.Hoteles, "id", "nombre", habitaciones.hotel);
            ViewBag.tipoHabitacion = new SelectList(db.tiposHabitaciones, "id", "nombre", habitaciones.tipoHabitacion);
            ViewBag.ubicacion = new SelectList(db.Ubicacion, "id", "nombre", habitaciones.ubicacion);
            return View(habitaciones);
        }

        // GET: Habitaciones/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Habitaciones habitaciones = db.Habitaciones.Find(id);
            if (habitaciones == null)
            {
                return HttpNotFound();
            }
            ViewBag.estado = new SelectList(db.Estados, "id", "nombre", habitaciones.estado);
            ViewBag.hotel = new SelectList(db.Hoteles, "id", "nombre", habitaciones.hotel);
            ViewBag.tipoHabitacion = new SelectList(db.tiposHabitaciones, "id", "nombre", habitaciones.tipoHabitacion);
            ViewBag.ubicacion = new SelectList(db.Ubicacion, "id", "nombre", habitaciones.ubicacion);
            return View(habitaciones);
        }

        // POST: Habitaciones/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,hotel,tipoHabitacion,nombre,descripcion,costo,impuesto,numeroAdultos,numeroNiños,totalPersonas,ubicacion,estado")] Habitaciones habitaciones)
        {
            if (ModelState.IsValid)
            {
                db.Entry(habitaciones).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Lista");
            }
            ViewBag.estado = new SelectList(db.Estados, "id", "nombre", habitaciones.estado);
            ViewBag.hotel = new SelectList(db.Hoteles, "id", "nombre", habitaciones.hotel);
            ViewBag.tipoHabitacion = new SelectList(db.tiposHabitaciones, "id", "nombre", habitaciones.tipoHabitacion);
            ViewBag.ubicacion = new SelectList(db.Ubicacion, "id", "nombre", habitaciones.ubicacion);
            return View(habitaciones);
        }

        // GET: Habitaciones/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Habitaciones habitaciones = db.Habitaciones.Find(id);
            if (habitaciones == null)
            {
                return HttpNotFound();
            }
            return View(habitaciones);
        }

        // POST: Habitaciones/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Habitaciones habitaciones = db.Habitaciones.Find(id);
            db.Habitaciones.Remove(habitaciones);
            db.SaveChanges();
            return RedirectToAction("Lista");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }     
    }
}

Agencia/Views/Habitaciones/Create.cshtml
@model Agencia.Models.Habitaciones

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Habitaciones</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.hotel, "hotel", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("hotel", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.hotel, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.tipoHabitacion, "tipoHabitacion", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("tipoHabitacion", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.tipoHabitacion, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.fechaEntrada, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.fechaEntrada, new { htmlAttributes = new { @class = "form-control", @type = "date" } })
            @Html.ValidationMessageFor(model => model.fechaEntrada, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.fechaSalida, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.fechaSalida, new { htmlAttributes = new { @class = "form-control", @type = "date" } })
            @Html.ValidationMessageFor(model => model.fechaSalida, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.nombre, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.descripcion, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.descripcion, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.costo, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.costo, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.costo, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.impuesto, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.impuesto, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.impuesto, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.numeroAdultos, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.numeroAdultos, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.numeroAdultos, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.numeroNiños, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.numeroNiños, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.numeroNiños, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.totalPersonas, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.totalPersonas, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.totalPersonas, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ubicacion, "ubicacion", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("ubicacion", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.ubicacion, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.estado, "estado", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("estado", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.estado, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index") |
    @Html.ActionLink("Back to List", "Lista")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Agencia/Views/Habitaciones/Delete.cshtml
@model Agencia.Models.Habitaciones

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Habitaciones</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.costo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.costo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.impuesto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.impuesto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.numeroAdultos)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.numeroAdultos)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.numeroNiños)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.numeroNiños)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.totalPersonas)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.totalPersonas)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Estados.nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Estados.nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Hoteles.nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Hoteles.nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tiposHabitaciones.nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tiposHabitaciones.nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ubicacion1.nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ubicacion1.nombre)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Agencia/Views/Habitaciones/Details.cshtml
@model Agencia.Models.Habitaciones

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Habitaciones</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Habitación
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nombre)
        </dd>

        <dt>
            Descripción
        </dt>

        <dd>
            @Html.DisplayFor(model => model.descripcion)
        </dd>

        <dt>
            Costo
        </dt>

        <dd>
            @Html.DisplayFor(model => model.costo)
        </dd>

        <dt>
            Impuesto
        </dt>

        <dd>
            @Html.DisplayFor(model => model.impuesto)
        </dd>

        <dt>
            Número de Adultos
        </dt>

        <dd>
            @Html.DisplayFor(model => model.numeroAdultos)
        </dd>

        <dt>
            Número de Niños/Niñas
        </dt>

        <dd>
            @Html.DisplayFor(model => model.numeroNiños)
        </dd>

        <dt>
            Total Personas
        </dt>

        <dd>
            @Html.DisplayFor(model => model.totalPersonas)
        </dd>

        <dt>
            Hotel
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Hoteles.nombre)
        </dd>

        <dt>
            Habitación
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tiposHabitaciones.nombre)
        </dd>

        <dt>
            Ubicación
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ubicacion1.nombre)
        </dd>

        <dt>
            Estado
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Estados.nombre)
        </dd>

    </dl>
</div>
<p>
    @if (Convert.ToInt32(Session["rol"]) == 1)
    {
        @Html.ActionLink("Editar", "Edit", new { id = Model.id })
    }
    @*@Html.ActionLink("Regresar", "Index") |*@
    | <a OnClick="javascript: return history.back()" style="cursor:pointer">Regresar</a> |
    @Html.ActionLink("Reservar", "../Reservas/Create", new { id_habitacion = Model.id, id_hotel = Model.hotel })
</p>

Agencia/Views/Habitaciones/Index.cshtml
@model IEnumerable<Agencia.Models.Habitaciones>

@using Agencia.Models;

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Reservar</h3>

@*<p>
        @Html.ActionLink("Create New", "Create")
    </p>*@
@*<table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.descripcion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.costo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.impuesto)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.numeroAdultos)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.numeroNiños)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.totalPersonas)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Estados.nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Hoteles.nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.tiposHabitaciones.nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Ubicacion1.nombre)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.descripcion)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.costo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.impuesto)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.numeroAdultos)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.numeroNiños)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.totalPersonas)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Estados.nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Hoteles.nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.tiposHabitaciones.nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Ubicacion1.nombre)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.id }) |
                    @Html.ActionLink("Details", "Details", new { id = item.id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.id })
                </td>
            </tr>
        }




    </table>*@


@*<script type="text/javascript">
    function ShowHide() {
        var value = document.getElementById('filtro').value;
        var theControl_SearchString = document.getElementById("SearchString");
        var theControl_dateString = document.getElementById("dateString");        
        if (value == "hotel" || value == "ciudad" || value == "totalPersonas") {
            theControl_SearchString style.display = "block";
            theControl_dateString.style.display = "none";            
        }
        else if (value == "fechaEntrada" || value == "fechaSalida") {
            theControl_SearchString.style.display = "none";
            theControl_dateString.style.display = "block";            
        }            
    }
</script>*@

<div class="container">
    <div class="row">
        <form asp-controller="Habitaciones" asp-action="Index">
            <h4>Filtrar por:</h4>
            <div class="col-lg-4">
                <select class="form-control" name="filtro" id="filtro">   @*onchange="ShowHide();"*@
                    <option value="hotel">Hotel</option>
                    <option value="fechaEntrada">Fecha entrada</option>
                    <option value="fechaSalida">Fecha salida</option>
                    <option value="totalPersonas">Cantidad personas</option>
                    <option value="ciudad">Ciudad</option>
                </select>
            </div>
            <div class="col-lg-4">                              
                <input type="text" class="form-control" id="SearchString" name="SearchString" style="display:block" />
            </div>
            <div class="col-sm-2">
                <input type="submit" value="Filter" />
            </div>
        </form>
    </div>
    <br />
    <div class="row">
        @foreach (var item in Model)
        {
            <div class="col-lg-5">
                <div class="tarjeta">
                    <div class="titulo">@Html.DisplayFor(modelItem => item.Hoteles.nombre)</div>
                    <div class="cuerpo">
                        <img src="https://images.trvl-media.com/lodging/39000000/38710000/38704000/38703955/820d83c5.jpg?impolicy=resizecrop&rw=1200&ra=fit" width="200" alt="muestra">
                        <div>Ciudad: @Html.DisplayFor(modelItem => item.Hoteles.ciudad)</div>
                        <div>Precio: COP @Html.DisplayFor(modelItem => item.costo) por noche</div>
                        <div>Impuestos: @Html.DisplayFor(modelItem => item.impuesto)</div>
                    </div>
                    <div class="pie">
                        @Html.ActionLink("Detalles/Reservar", "Details", new { id = item.id })
                        @*<a href="@Html.ActionLink("Mas información", "Details")">Más información</a>*@
                    </div>
                </div>
                <br />
            </div>
        }
    </div>
    <h3>Reservas históricas</h3>
    <div class="row">
        <table class="table">
            <tr>
                <th>Usuario</th>
                <th>Hotel</th>
                <th>Habitacion</th>
                <th>Fecha</th>
                <th>Ciudad Destino</th>
            </tr>
            @foreach (ModelNew item in (ModelNew[])ViewBag.reservas)
            {
                <tr>
                    <td>@item.nombre_usuario</td>
                    <td>@item.nombre_hotel</td>
                    <td>@item.nombre_habitacion</td>
                    <td>@item.fechaEntrada</td>
                    <td>@item.ciudadDestino</td>
                    <td>
                        @Html.ActionLink("Editar", "../Reservas/Edit", new { id = @item.id }) |
                        @Html.ActionLink("Detalles", "../Reservas/Details", new { id = @item.id }) |
                        @Html.ActionLink("Eliminar", "../Reservas/Delete", new { id = @item.id })
                    </td>
                </tr>
            }
        </table>
    </div>
</div>